name: Swift

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Install swiftlint
      run: |
        brew update
        brew install swiftlint
    
    - name: Lint
      run: swiftlint
    
    - name: Build
      run: swift build -v
    
    - name: Run tests
      run: swift test -v